### ISSUE TITLE
Link to support server invalid

### ISSUE THREAD

**Issue by circuitsacul** [xShadoww/eris-starboard#3]
The link discord invite at the end of the README is invalid

**Comment by xShadoww** [comment]
Currently working on a new bot, you can join here **[https://discord.gg/ffvUh2s](https://discord.gg/ffvUh2sl)**

**Comment by CircuitSacul** [comment]
I clicked that link, I get an invalid invite link. Maybe it expired?

**Comment by xShadoww** [comment]
Apologies, here you go: [https://discord.gg/UbbCCuh](https://discord.gg/UbbCCuh)
